// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/gigachat/agent': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/gigachat/agent.post').default>>>>
    }
    '/api/redis/get-service': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redis/get-service.post').default>>>>
    }
    '/api/redis/history': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redis/history.get').default>>>>
    }
    '/api/redis/save-message': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/redis/save-message.post').default>>>>
    }
    '/api/yclients/auth/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yclients/auth/login.post').default>>>>
    }
    '/api/yclients/get-company-servies': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yclients/get-company-servies.get').default>>>>
    }
    '/api/yclients/recommended-services': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yclients/recommended-services.get').default>>>>
    }
    '/api/yclients/update-record-comment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/yclients/update-record-comment.post').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt/dist/core/runtime/nitro/handlers/renderer').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}