// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 11/5/2025, 6:31:28 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/plugins/**/*.{js,ts,mjs}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/composables/**/*.{js,ts,mjs}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/utils/**/*.{js,ts,mjs}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/gleb/CLionProjects/FIRETECHNO/YCLIENTS-QUIZ/myproject/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;